import type { Metadata } from "next";

import { getServerSession } from "next-auth";
import Sidebar from "../components/Sidebar";
// <<<<<<< HEAD

// =======
import { AUTH_CONFIG } from "../lib/auth";

// >>>>>>> 111d179ad580ae9ba33c99443d11b940fc2a3551
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession(AUTH_CONFIG);

  return (
    // <<<<<<< HEAD
    <>
      <div className="flex flex-row w-full">
        {session ? <Sidebar /> : null}
        {children}
      </div>
      {/* <main>
        {children}
        {JSON.stringify(session)}
        {session ? <Sidebar /> : null}
      </main> */}
    </>
    // >>>>>>> 111d179ad580ae9ba33c99443d11b940fc2a3551
  );
}
