import type { Metadata } from "next";

import { getServerSession } from "next-auth";
import Sidebar from "../components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession();

  return (
    <div className="flex flex-row w-full">
      {session ? <Sidebar /> : null}
      {children}
    </div>
  );
}
