import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

import { getServerSession } from "next-auth";
import SessionProvider from "@/db/SessionProvider";
import Sidebar from "./components/Sidebar";
// import Login from "./login/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Login /> */}

        <SessionProvider session={session}>
          <Navbar />
          <div className="flex flex-row">
          <Sidebar />
            {children}
          </div>
        </SessionProvider>

      </body>
    </html>
  );
}
